<LandingPage/>
<App/>
    <Home/>
        <NavBar/>
        <Footer/>
            <Header/>
            <Section1/>
            <Section2/>
                <Carousel/>
            <Section3/>
        <About/>
            <Header/>
            <Section1/>
            <Section2/>
            <Section3/>
            <Section4/>
                <Carousel/>
        <Services/>
            <Header/>
            <Section/>
                <Schedule/>
                <Retreats/>
                <Online/>
                <Photography/>
        <Blog/>
            <Header/>
            <Section1/>
            <Section2/>
                <LatestPost/>
                <RecentPosts>
                    <Post/>
                        <IMG/>
                        <Title/>
                        <Date/>
            <Section3/>
                <Comments/>
                    <Comment/>
        <Contact/>
            <Header/>
            <Section1/>
                <ContactForm/>
                <Content/>
